-- create test user with permissions
ALTER SESSION SET CONTAINER = xepdb1;
CREATE USER test IDENTIFIED BY test;
ALTER USER test QUOTA unlimited ON SYSTEM;
GRANT CREATE SESSION, CONNECT, RESOURCE, DBA TO test;
GRANT ALL PRIVILEGES TO test;
